name: expense_tracker_app
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  firebase_storage: any
  google_sign_in: any
  provider: ^6.1.5+1
  fl_chart: ^0.70.0
  google_fonts: ^8.1.0
  shimmer: ^3.0.0
  intl: ^0.20.2
  local_auth: ^2.3.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
